<?php

namespace backend\modules\sms\models;

use Yii;

/**
 * This is the model class for table "message".
 *
 * @property string $message_id
 * @property string $content
 * @property string $phone
 * @property integer $status
 * @property string $remark
 */
class Message extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'message';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content', 'phone'], 'required'],
            [['status'], 'integer'],
            [['create_time', 'update_time'], 'safe'],
            [['content'], 'string', 'max' => 512],
            [['phone'], 'string', 'max' => 16],
            [['remark'], 'string', 'max' => 64],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'message_id' => Yii::t('app', '短信编号'),
            'content' => Yii::t('app', '短信内容'),
            'phone' => Yii::t('app', '手机号'),
            'status' => Yii::t('app', '1:成功，2:失败'),
            'remark' => Yii::t('app', '备注信息'),
            'create_time' => Yii::t('app', '创建时间'),
            'update_time' => Yii::t('app', '修改时间'),
        ];
    }

    public static function send($mobile, $msg, $needstatus = 'true', $sender = '', $type = 'json'){
        $api_send_url = Yii::$app->params['smsConf.apiSendUrl'];

        $api_username = Yii::$app->params['smsConf.apiUsername'];
        $api_password = Yii::$app->params['smsConf.apiPassword'];

        $postArr = [
            'name' => $api_username,
            'pswd' => $api_password,
            'msg' => $msg,
            'mobile' => $mobile,
            'needstatus' => $needstatus,
            'sender' => $sender,
            'type' => $type
        ];
        $ret_data = request($api_send_url,$postArr);
        $ret = json_decode($ret_data,true);
        $model = new Message();
        if (isset($ret['respstatus']) && $ret['respstatus']==0) {   //发送成功
            $model->setAttributes(['content'=>$msg,'phone'=>$mobile,'status'=>1]);

            if (!$model->save()) {
                return false;
            }

            return true;
        }

        //发送失败
        $model->setAttributes(['content'=>$msg,'phone'=>$mobile,'status'=>2,'remark'=>isset($ret['msgid'])?$ret['msgid']:NULL]);

        if (!$model->save()) {
            return false;
        }

        return false;
    }
    
    public function beforeSave($insert)
    {
        $this->update_time = date('Y-m-d h:i:s');
        if ($insert) {
            $this->create_time = date('Y-m-d h:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
